name: FastAPI-Test-CI

on:  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env1
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_LOG_ACCESS_KEY: ${{ secrets.AWS_LOG_ACCESS_KEY }}
      AWS_LOG_SECRET_KEY: ${{ secrets.AWS_LOG_ACCESS_KEY }}
      USER_BUCKET_NAME: ${{ secrets.USER_BUCKET_NAME }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - 
        name: Load file from S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://damg-7245-projects/data-store/airflow_scrape_data.db
          destination: ./fastapiapp/airflow_scrape_data.db
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: us-east-1
      -
        name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      -
        name: Install pipenv
        run: pip install pipenv
      -
        name: Run tests
        working-directory: ./fastapiapp
        run: |
          pipenv install -r requirements.txt
          pipenv run pytest -v                          
        # Running pytest
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./Fast\ API    # path to dockerfile
      #     # file: Dockerfile
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKERHUB_USERNAME }}/fast_api_app:latest
      #       ${{ secrets.DOCKERHUB_USERNAME }}/fast_api_app:${{ steps.commit.outputs.short }}
      #     # Change the container image "fast_api_app"